content:

  clanky:
    label: Články
    type: collection
    path: clanky
    format: json
    fields:
      title:
        label: Nadpis
        type: string

      date:
        label: Datum
        type: date

      tag:
        label: Tagy
        type: multiselect
        options:
          - Novinka
          - Projekt
          - Linux
          - Ostatní

      desc:
        label: Krátký popis
        type: text

      url:
        label: URL
        type: string
