content:
  pages:
    label: Stránky
    type: collection
    path: content/pages
    fields:
      title:
        label: Název
        type: text

      slug:
        label: URL slug
        type: slug
        from: title

      body:
        label: Obsah
        type: rich-text

      published:
        label: Publikováno
        type: boolean
        default: false

  clanky:
    label: Články
    type: collection
    path: clanky
    format: json
    fields:
      title:
        label: Nadpis
        type: string

      date:
        label: Datum
        type: date

      tag:
        label: Tagy
        type: multiselect
        options:
          - Novinka
          - Projekt
          - Linux
          - Ostatní

      desc:
        label: Krátký popis
        type: text

      url:
        label: URL
        type: string
