content:
  - name: clanky
    label: Články
    type: collection
    path: clanky
    format: markdown
    filename: "{{number padding=5}}-{{slug title}}"
    fields:
      - name: title
        label: Nadpis
        type: string

      - name: date
        label: Datum
        type: date

      - name: releaseDate
        label: Datum vydání
        type: date

      - name: releaseTime
        label: Čas vydání
        type: string
        placeholder: 15:30
        help: Hodiny:Minuty (např. 09:00 nebo 23:30)

      - name: tags
        label: Tagy
        type: select
        options:
          multiple: true
          values:
            - Novinka
            - Projekt
            - Linux
            - Ostatní

      - name: desc
        label: Krátký popis
        type: text

      - name: body
        label: Obsah článku
        type: rich-text
        options:
          image: true
          heading: true
          bold: true
          italic: true
          bulletList: true
          orderedList: true
          link: true
          blockquote: true
          code: true
          simple: false

      - name: url
        label: URL
        type: string
