title: Moje tajné pískoviště
theme: minima
baseurl: "/Moje-tajne-piskoviste"


# Tímto kompletně vypneš zobrazení ikony GitHubu a odkazu vpravo:
github_username: null

collections:
  clanky:
    output: true
    permalink: /clanky/:title/
  projekty:      # Tímto zakládáme novou sekci
    output: true
    permalink: /projekty/:title/